### ISSUE TITLE
Two steps hydration

### ISSUE THREAD

**Issue by blanchonvincent** [Ocramius/Doctrine2StepHydration#1]
Hey Marco

I was looking the file https://github.com/Ocramius/Doctrine2StepHydration/blob/master/multi-step-hydration.php

It seems you never used the result of the query

``` php
$entityManager
    ->createQuery('
        SELECT
            u, s
        FROM
            ' . User::class . ' u
        LEFT JOIN
            u.sessions s
    ')
    ->getResult();
```

I guess it's a mistake?
You should concat the 2 queries to get one users list fully hydrated, right?

**Comment by Ocramius** [comment]
No mistake: this simply re-hydrates data that is already in the UoW.

Did you read the related article?

**Comment by blanchonvincent** [comment]
@Ocramius Gotcha now :p I faced to the case, thx :)
